/* Home screen posts */
export const LOAD_HOME_POSTS_SUCCESS = 'LOAD_HOME_POSTS_SUCCESS'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'

/*Map screen posts*/
export const LOAD_MAP_POSTS_SUCCESS = 'LOAD_MAP_POSTS_SUCCESS'
export const ADD_MAP_SUCCESS = 'ADD_MAP_SUCCESS'

/* New post */
export const TOGGLE_NEW_POST_MODAL = 'TOGGLE_NEW_POST_MODAL'
export const CHANGE_SPLASH_RANGE = 'CHANGE_SPLASH_RANGE'
export const CHANGE_NEW_POST_TYPE = 'CHANGE_NEW_POST_TYPE'
export const NEW_POST_ADD_INITIATE = 'NEW_POST_ADD_INITIATE'
export const NEW_POST_ADD_SUCCESS = 'NEW_POST_ADD_SUCCESS'

